### PR TITLE
Add Bhavesh in the contributors.md

### PR DESCRIPTION
**Pull request by bhaveshgoyal182**

### CODE REVIEW

**Comment by bhaveshgoyal182** [comment]
Hey @apoorvdwi ,
Can you help me with this ?

**Comment by apoorvdwi** [comment]
Change the image format to jpeg/jpg/png and resolve conflicts

**Comment by bhaveshgoyal182** [comment]
> Change the image format to jpeg/jpg/png and resolve conflicts

Okay let me try to fix that.

**Comment by bhaveshgoyal182** [comment]
> > Change the image format to jpeg/jpg/png and resolve conflicts
> 
> Okay let me try to fix that.

I am unable to change the photo in the folder in the same PR.
Can you help me out?

**Comment by apoorvdwi** [comment]
Just delete the image in you forked repo and add a new one and change the path in Contributors2021Section.vue file

**Comment by bhaveshgoyal182** [comment]
Thanks @apoorvdwi  for helping me I learnt a new thing over here i.e. how to make a change to an existing PR.

**Pull request merged**
