### PR TITLE
Added details

### PR DESCRIPTION
**Pull request by mrunankpawar**

### CODE REVIEW

**Comment by mrunankpawar** [comment]
I'm not getting the reason why the deployment failed.

**Comment by apoorvdwi** [comment]
In the filename its .PNG where as in file you have written .png

**Comment by mrunankpawar** [comment]
I made the required changes and then it got into merge conflict. I tried to resolve the conflict but again the deployment has failed.

**Comment by apoorvdwi** [comment]
Check line 154 of Contributors2021Section, opening brace is missing

**Pull request merged**
